export const words = [
  "ox", "pi", "go", "if", "up",
  "ape", "bug", "cup", "elm", "fig",
  "atom", "blip", "dusk", "grit", "haze",
  "ghost", "ivory", "joker", "lemon", "moose",
  "breeze", "cactus", "falcon", "garlic", "orchid",
  "blanket", "eclipse", "hammock", "lantern", "paradox",
  "catalyst", "electron", "fracture", "labyrinth", "xylophone",
  "red fox", "old map", "big sky", "dry ice", "hot tea",
  "sea fog", "dim sun", "raw gem", "new day", "tin cup",
  "blue haze", "cold snap", "dark moon", "deep echo", "faint glow",
  "iron gate", "jade ring", "keen edge", "last wolf", "pale dust",
  "sharp wind", "quiet tide", "golden elm", "broken oar", "silver fox",
  "loud river clay", "frozen amber sky", "gentle morning dew",
  "hidden crystal cave", "ancient marble tower",
  "burning copper sun", "silent winter fog", "twisted iron gate",
  "crimson velvet dawn", "hollow mountain peak",
  "drifting autumn leaf", "polished cedar plank",
  "scattered pebble trail", "luminous coral reef",
  "withered oak branch", "endless gravel road",
  "flickering neon sign", "crumbling sandstone wall",
  "tangled copper wire", "shattered porcelain vase",
  "bold", "crisp", "fern", "gulp", "hint",
  "jolt", "knob", "lava", "mink", "nook",
  "swift creek", "grand arch", "steep cliff", "fresh mint", "warm glow",
  "rapid pulse", "stark contrast", "vivid dream", "woven thread", "brittle glass",
];
