export const words = [
  "Wait",
  "The kettle hums softly",
  "Rain tapped the glass twice",
  "Blue",
  "Not yet",
  "Keys jingled in his coat",
  "Run",
  "Coffee first",
  "Yes",
  "Almost midnight",
  "Stop",
  "Go on",
  "Now",
  "Too loud",
  "Hi",
  "Same time tomorrow?",
  "No",
  "Maybe later",
  "The bus left early",
  "Ice melts fast here",
  "She waved once, then left",
  "Quiet room, loud thoughts",
  "Paper rustled in the hall",
  "He checked his watch again",
  "Stars hid behind thin clouds",
  "Warm bread, cold butter",
  "The cat yawned, unimpressed",
  "Fog rolled down the street",
  "Try again in the morning",
];
